name: build-n-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out reposity code
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.21.3
      - run: go install
      - run: go build -o api .
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: go test ./...
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Deploying Go app"
